### ISSUE TITLE
acknowledgements section missing from marked up files

### ISSUE THREAD

**Issue by nathandunn** [bioentity/Bioentity.link#11]
FYI @nickstiffler

**Comment by nickstiffler** [comment]
Is in the original?

**Comment by nathandunn** [comment]
Its from the email thread earlier today:

![image](https://user-images.githubusercontent.com/751274/58830622-96858c00-85ff-11e9-90aa-b21ed6c37852.png)

**Comment by nickstiffler** [comment]
It sounds like acknowledgments are there after all.
