### ISSUE TITLE
comments get swallowed

### ISSUE THREAD

**Issue by nathandunn** [bioentity/Bioentity.link#12]
1.      Bioentity linked XML is missing the query markers (yellow highlight below). We need these for pdf composition.

 
```
Original Linked XML:

loss-of-function
                    leads to supplementary neural-type cells at the expense<!-- Q1 --> of accessory
                    cells<!-- DBComment1 -->. Our data indicate that Ttk69 (1) promotes cell cycle

 

Bioentity Linked XML:

loss-of-function
                    leads to supplementary neural-type cells at the expense of accessory cells. Our
                    data indicate that Ttk69 (1) promotes cell cycle
```
 

 

2.      Our export file has a processing instruction for the display affiliations that was removed from the Bioentity linked XML. I believe we need to keep this processing instruction in our XML for pdf generation.

 

Michelle, if this Affiliation Display is no longer needed for composition, let us know.

 
```
Original Linked XML:

 

</counts>
            <!--* Laboratory of Developmental Biology, Institut de Biologie Paris-Seine, Center National de la Recherche Scientifique and <sup>&#x2020;</sup> Laboratory of Developmental Biology, Sorbonne-Universit&#x00E9;, UMR 7622, F-75005 Paris, France-->
        </article-meta>

 

Bioentity Linked XML:

</counts>
        </article-meta>
```

**Comment by nickstiffler** [comment]
"you can always convert those to "%%— Q1 —%%" or something like this and convert it back on export. " - Nathan

**Comment by nathandunn** [comment]
@nickstiffler  Here is a paper that fails (most of the other papers don't per email):

https://bioentity.link/#/publication/10.1534/genetics.119.777734


[file_xml.zip](https://github.com/bioentity/Bioentity.link/files/3253252/file_xml.zip)

**Comment by nathandunn** [comment]
777734 upload fine, but then on saving it loses its links. 

My guess is the XML is getting parsed and re-save, but no idea why its removing comments.  Maybe a different header or file type?

**Comment by nickstiffler** [comment]
Just tested the new texture, and it dumps the comments `<!-- -->` as well.

**Comment by nathandunn** [comment]
Its really just the one pub.   

It also only creates that error AFTER you do linking. 

Nathan

**Comment by nickstiffler** [comment]
I guess I am not seeing the error.

**Comment by nathandunn** [comment]
Do you want to give me a quick call and I can show you how to reproduce it?

**Comment by nickstiffler** [comment]
Sure.
