### ISSUE TITLE
sec tags lose id and sec-type on export

### ISSUE THREAD

**Issue by nickstiffler** [bioentity/Bioentity.link#18]
I confirmed that texture imports it properly but for some reason the original id and sec-type attributes are missing on export.

**Comment by nathandunn** [comment]
@nickstiffler  if you add a SINGLE link (e.g., right-click a word and link it), you can see that it then screws up the `<sec`.  I'm wondering if you attempt another type of edit / `write` what it will do.

**Comment by nickstiffler** [comment]
It seems to be happening in `onCreateText(e)` in `texture/node_modules/substance/ui/ContainerEditor.js. I don't have any more time to work on it though.

**Comment by nickstiffler** [comment]
It seems to be happening in `create(nodeData)` in `texture/node_modules/substance/model/Document.js`. `section` and `title` are the only things that get a new ID here.

**Comment by nickstiffler** [comment]
I found the problem. Texture converts the `section` tags into something else on import and then converts it back on export. If I disable this, the problem goes away.

**Comment by kyook** [comment]
Awesome! Thanks Nick!

**Comment by nathandunn** [comment]
That rocks!
