### ISSUE TITLE
make delete button in publisher panel less accessible

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#19]
or spaced away from other buttons.  I can see myself clicking on the red X by accident as I navigate around each paper in the column, playing with the various filters and sorting etc.  At this point, I would very much not like to lose any data that we have for the live papers.

**Comment by nickstiffler** [comment]
It should prompt you to confirm delete, although I know some people have a habit not reading popups.

**Comment by kyook** [comment]
ok, the pop up is clear enough.
