### ISSUE TITLE
way to supply identifiers.org links outside of texture app?

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#25]
We need a way to create links on an individual basis for objects outside of the texture app. 

1. Sheridan (publishers) will request hyperlinks to objects during the proof stage. 
2. Curators will request links to be added during the proof stage. 

Both entail the curator looking up the identifier and manual constructing the link that needs to be embedded. This is clunky, error prone and not trackable.  Getting the identifiers.org construction is not straightforward. 

For example: 
https://bioentity.link//#/publication/10.1534/genetics.119.302509
Links for additional objects requested by the authors were supplied by Phani.  These links do not follow the identifiers.org construction.   

'sp' (speck): http://flybase.org/reports/FBgn0003466
'f' (forked): http://flybase.org/reports/FBgn0262111
'b' (black):  http://flybase.org/reports/FBgn0000153
'vg'(vestigial): http://flybase.org/reports/FBgn0003975
'h' (hairy):  http://flybase.org/reports/FBgn0001168
'e' (ebony):  http://flybase.org/reports/FBgn0000527

**Comment by nickstiffler** [comment]
I am not sure what action is being requested here, but the format for those would be:
http://identifiers.org/bioentitylink/FB:FBgn0003466
http://identifiers.org/bioentitylink/FB:FBgn0262111
http://identifiers.org/bioentitylink/FB:FBgn0000153
http://identifiers.org/bioentitylink/FB:FBgn0003975
http://identifiers.org/bioentitylink/FB:FBgn0001168
http://identifiers.org/bioentitylink/FB:FBgn0000527

**Comment by kyook** [comment]
We need to know the url constructors to manually construct these links for GSA during the proof stage. 

It looks like these would be
http://identifiers.org/bioentitylink/<db:><ID>

**Comment by nickstiffler** [comment]
I tried `http://identifiers.org/bioentitylink/RGD:1626009` but it didn't resolve. According to the email Nathan fowarded us, RGD should be in there:
`Other contact: Karen Yook (karyook@gmail.com). We are trying to set this up for each prefix of data. We will have WB: (already included with this request). Additional prefixes we wish to request (using the same URL scheme) are ZFIN: , SGD: , FB: , MGI:, RGD:, GO:, CGC:, CHEBI:, ADDGENE: , POMBASE: . If we need to do subsequent requests (or if you have any other questions), please contact us. Thanks.`

**Comment by nickstiffler** [comment]
Link shows up in lexica view now:
![link](https://user-images.githubusercontent.com/2396480/65648664-0c02d700-dfb8-11e9-8ae4-8cda2ec14cda.png)

**Comment by kyook** [comment]
Cool! Thanks!
