### ISSUE TITLE
downloading both 'linked' and 'original' xmls from within bioentity.link downloads linked files

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#27]
I was trying to download an unlinked version of this paper - I wanted to check the fix Nick just put in that allows linking to entities that are followed by a hyphen (any other character?). 

Downloading both using the  'original' button returned a linked version of the xml rather than a version that does not have links, is there an easy way to upload a testable copy of  the unlinked version?  - I did not want to unlink the live version and test on that since I didn't want to alter any captured stats for it - or have Suzie test that one. 

I did not want to test it on the live article. 
https://bioentity.link//#/publication/10.1534/genetics.119.302435

**Comment by nickstiffler** [comment]
These buttons are misleading. They both return a linked version of the paper, but the "Linked" button returns a XML with the many fixes needed by GSA. The "Original" button returns the linked version exported from Texture. I will change their labels and add a button that actually returns the original document.

**Comment by kyook** [comment]
Ah! Thanks.  The third button will be very useful!

**Comment by nickstiffler** [comment]
I added a button for download the unlinked xml as well as clarified the wording of the existing buttons.
![download_xml](https://user-images.githubusercontent.com/2396480/64886726-b1fb2c80-d61b-11e9-89b3-407a1997e2c7.png)
