### ISSUE TITLE
journal metadata and editing tools disappear when scrolling to the end of the article

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#36]
I need to be able to link a term within the article without accessing the linking tool from the paper viewer header. In part because the header disappears if I've scrolled to the end of the paper or performed a search in the browser. Needing to link a term then scrolling up or readjusting the window to get back the header is not a scalable solution. The linking tool should be accessible when selecting a term in the text.

**Comment by nickstiffler** [comment]
Maybe it is a little better now. It is using set pixel sizes that may not be appropriate for all devices. It should auto-scale to the screen height, but I just reduced the heightt for now so it may fit in your screen a little better.

**Comment by kyook** [comment]
thanks!  I'll take a look

**Comment by kyook** [comment]
Works great!  Thanks!
