### ISSUE TITLE
new lexica objects should be added to its own lexicon source

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#37]
truncated terms are being linked (added to lexica) during QC, these should not be added to the main lexicon

![Screen Shot 2019-09-04 at 1 38 16 PM](https://user-images.githubusercontent.com/611610/64289554-44634800-cf19-11e9-9961-6e633e20c1cf.png)

**Comment by nickstiffler** [comment]
Changed behavior to not create new lexica object if mod id already exists. Should no longer be an issue, but it would be good to delete these so they don't get linked.

**Comment by kyook** [comment]
not sure how to find them other than looking through each lexicon.  what do you suggest?

**Comment by nickstiffler** [comment]
I can run a query and remove lexica with duplicate mod ids, but I may do some testing first to make sure it doesn't cause any unintended consequences. Alternatively, we can build new lexica/key word sets.
