### ISSUE TITLE
"send to publisher as ready" does not send to publisher for phanivg

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#40]
https://bioentity.link/#/publication/10.1534/genetics.119.302694

the fly curators submit the paper to the publisher and the links do go through validation however the paper doesn't seem to be sent, there is no notification that the paper is sent. I have not tried to send this paper to the publisher myself; however I was able to send the following two based on G3 alerting me that they did not get them.  

https://bioentity.link/#/publication/10.1534%2Fg3.119.400715
https://bioentity.link/#/publication/10.1534%2Fg3.119.400453

**Comment by nickstiffler** [comment]
The send to publisher workflow is more robust than it used to be. If phanivg or others aren't still experiencing issues, this can be closed.
