### ISSUE TITLE
paper is not showing in texture

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#41]
https://bioentity.link/#/publication/10.1534%2Fg3.119.400603

I took a look at the xml, but nothing pops out at me as to why it is not working. Would you take a look @nickstiffler?

**Comment by nickstiffler** [comment]
I think the problem is here:
```<contrib contrib-type="author">
<contrib-id contrib-id-type="orcid">http://orcid.org/0000-0001-7677-7228</contrib-id>
<name>
<surname>Manu</surname>
</name>
<xref ref-type="aff" rid="aff2">
<sup>†</sup>
</xref>
</contrib>```

There is no "given-name" element. Do you this person really has only one name?

**Comment by nickstiffler** [comment]
Texture seems to require it, but It looks like given-names is optional: https://jats.nlm.nih.gov/publishing/tag-library/1.1/element/name.html

**Comment by kyook** [comment]
GGG send a 'fixed' xml with a first name placeholder. @nickstiffler, might want to implement the same optionality for the micropub app?
