### ISSUE TITLE
Uncaught error: AnnotationCommand can't execute command for selection PropertySelection

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#50]
https://bioentity.link/#/publication/10.1534/g3.119.400730

I was linking this paper with the FB_gene keyword set, italic only. Some entities were linked, the linking was stalled, no entities show in the link list in the sidebar.

![Screen Shot 2019-11-04 at 10 29 40 AM](https://user-images.githubusercontent.com/611610/68147057-1d5fcd00-feee-11e9-9ce2-033f022a6f59.png)

**Comment by nickstiffler** [comment]
I added some code to handle the error. I think the problem is that it links `parkin` then it tries to link `park`, but there is already a link. Thanks for the screenshot. It is helpful.
