### ISSUE TITLE
Too many links being generated, displayed in Menu

### ISSUE THREAD

**Issue by suzialeksander** [bioentity/Bioentity.link#53]
10.1534/g3.119.400606 has the entity "pos5" appear 8 times.  The link menu on the right side tells me there are 518 links to pos5. I would expect the menu to tell me there are 8 links.  

Not the only entity to be treated this way, but probably the most egregious.

**Comment by kyook** [comment]
Hi @nickstiffler https://github.com/bioentity/papers/issues/1303, could you take a look at this paper and its issues?  You might need to get @suzialeksander online to go through everything.
