### ISSUE TITLE
getting list of entities and links 

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#57]
@nickstiffler I need to get a list of all protein entities and their links for this paper: https://bioentity.link//#/publication/10.1534/g3.119.400850 is there a way to do that? 

For some reason, the proteins did not get linked when I ran the keyword set, so now I need to send a list to the publisher to add them to the proof. Unfortunately, there are so many!

**Comment by nickstiffler** [comment]
It looks like you re-linked with just proteins. Is this problem repeatable or did it just happen randomly?
I can run a database query and produce a table with entity ID, public name, number of instance and URL. Anything else?

**Comment by kyook** [comment]
It seemed random.  I'm pretty sure I ran the comprehensive WB keyword set, but didn't notice that the proteins were not linked.  Regardless, I reverted the comprehensive WB keyword set linking and ran just the wb protein keyset to get the list of proteins and links. if you can run the query you suggest that would be great. I can send the publisher the list. thanks!

**Comment by kyook** [comment]
@nickstiffler let me know when the list is ready. Thanks!

**Comment by nickstiffler** [comment]
Will Monday be too late?

**Comment by kyook** [comment]
That is fine. Thanks!
~~~~
Karen Yook

Curator / Editor
WormBase Caltech / microPublication
email: kyook@caltech.edu
email: karen@wormbase.org
email: karen.yook@micropublication.org
skype name: wbkaren
tel: +1(415)306-4150

On Sat, Dec 21, 2019 at 9:38 PM nickstiffler <notifications@github.com> wrote:
>
> Will Monday be too late?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nickstiffler** [comment]
Query for future reference:
```MATCH (p:Publication)-[]-(m:Markup)-[]-(l:Lexicon) WHERE p.title = 'Wnt Signaling Drives Ectopic Gene Expression and Larval Arrest in the Absence of the Caenorhabditis elegans DREAM Repressor Complex' RETURN count(m),l.publicName,l.externalModId,('https://identifiers.org/bioentitylink/WB:' + l.externalModId + '?doi=10.1534/g3.119.400850')```

**Comment by kyook** [comment]
Hey @nickstiffler is the list available? or do I have to run the query? If so, how/where do I do that?

**Comment by nickstiffler** [comment]
I sent the list to you as an attachment in an email on 12/23.

**Comment by kyook** [comment]
Ugh, sorry! And thank you.
