### ISSUE TITLE
please add arabidopsis and xenopus to the species lexicon creation dropdown

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#62]
![Screen Shot 2020-01-15 at 4 29 17 PM](https://user-images.githubusercontent.com/611610/72473252-489b4e00-37b4-11ea-936b-131e76689653.png)

**Comment by nickstiffler** [comment]
Add species works again
![species](https://user-images.githubusercontent.com/2396480/74502526-acdc2b00-4ea2-11ea-8d4f-82f03279e80b.png)

**Comment by kyook** [comment]
cool!
