### ISSUE TITLE
saving edits to the texture article are not getting saved

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#64]
I've gone through an redid all the italics, I've saved along the way, but many of the edits did not get saved. When I refresh or close and return to the article, half or more of the edits I made were not saved.  I dont' think I will be able to fix the italics by making edits to the texture view, it is taking way too long with no security of the edits being captured

https://github.com/bioentity/papers/issues/1338

**Comment by kyook** [comment]
looking at the xml going to Genetics, I'm seeing that some of the italics tags look like this: 
<italic id="italic-85ccb3b36b1bb0daaf2ffc755dc7744b">lin-29</italic>

**Comment by nickstiffler** [comment]
Not italicized?

**Comment by nickstiffler** [comment]
Oh! That is an easy fix.

**Comment by kyook** [comment]
this link did not get entered properly and I cannot unlink it. 
'<ext-link ext-link-type="uri" xlink:href="">deSi6</ext-link>'

**Comment by nickstiffler** [comment]
The link is missing. How did that happen?

**Comment by kyook** [comment]
I was linking it, in the process the popup window that allows the linking disappeared, I couldn't find it again, and I couldn't delete the link, I am not able to do anything more to the entity. I guess that this point I will start completely over with a new round of linking.

**Comment by nickstiffler** [comment]
When you say "linking it" do you mean linking the whole doc, or just creating a single link?
I can edit the xml if needed. Just let me know what needs to be edited.

**Comment by kyook** [comment]
I downloaded the unlinked version of the article sent by Sheridan and
used a text editor to fix the italic tags
and changed the doi in the doi tag to 10.1534/genetics.119.302860fix
so I could upload and link it in the system

then uploaded the article with new name, linked it and did a few more
italic modifications using texture.  Here are the linked raw and
linked processed files.
At this point, I'm not sure about the best thing to do. All the links
have the new doi title, which will need to be changed if I send them
the file via email.

If you could fix the original file already in the system
10.1534/genetics.119.302860 to have the links I put in, that would be
great. I dont' know how you would deal with the italics. I added a
lot, which I don't think they will like.

Let me know what you think is best. I will have to fix the other worm
papers as well.
~~~~
Karen Yook

Curator / Editor
WormBase Caltech / microPublication
email: kyook@caltech.edu
email: karen@wormbase.org
email: karen.yook@micropublication.org
skype name: wbkaren
tel: +1(415)306-4150

On Wed, Feb 5, 2020 at 4:09 PM nickstiffler <notifications@github.com> wrote:
>
> I put in a fix to remove the italic id. Thanks for catching that. They would have complained.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nickstiffler** [comment]
I don't think I can replace the original because all the links are associated with this publication, but it sounds like if word the "fix" was removed from the DOI, it will now be ready to send.

**Comment by kyook** [comment]
ok, I will remove it from the xml links and title and send it.
~~~~
Karen Yook

Curator / Editor
WormBase Caltech / microPublication
email: kyook@caltech.edu
email: karen@wormbase.org
email: karen.yook@micropublication.org
skype name: wbkaren
tel: +1(415)306-4150

On Wed, Feb 5, 2020 at 6:10 PM nickstiffler <notifications@github.com> wrote:
>
> I don't think I can replace the original because all the links are associated with this publication, but it sounds like if word the "fix" was removed from the DOI, it will now be ready to send.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
