### ISSUE TITLE
Link summary button - author field comes up as 'null'

### ISSUE THREAD

**Issue by aoifelarkin** [bioentity/Bioentity.link#67]
- first mentioned this issue to @kyook in https://github.com/bioentity/papers/issues/1348.

Thanks for the download option of the linked entities in the article, looks good! Only thing I noticed is that the 'author' field in any articles I've QC'd is coming up as 'null'.

e.g.:
![Screenshot 2020-02-27 at 13 49 50](https://user-images.githubusercontent.com/22240137/75451379-6093ef00-5968-11ea-96d6-a8dd220f719f.png)

**Comment by nickstiffler** [comment]
I was actually aware of this. The authors section of the xml isn't currently being parsed by the app, so they aren't available here. I will plan on adding that.
