### ISSUE TITLE
No longer able to see lexica

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#72]
I see the new source class list, but I can't see any of the actual preexisting lexica.  I can see keyword sets and can open them though.

![Screen Shot 2020-03-08 at 8 53 55 PM](https://user-images.githubusercontent.com/611610/76174666-1f2cec00-617f-11ea-89ad-ee7779335df6.png)
![Screen Shot 2020-03-08 at 8 54 23 PM](https://user-images.githubusercontent.com/611610/76174668-20f6af80-617f-11ea-92e5-7dafc6276c85.png)

**Comment by nickstiffler** [comment]
It is looking for `TRANSGENIC_TRANSPOSON`, but that was removed.

**Comment by nickstiffler** [comment]
It is fixed now. I updated the existing lexicon sources to be `TRANSPOSON`, `INSERTION` and `PHENTYPE`.
