### ISSUE TITLE
making linking case insensitive

### ISSUE THREAD

**Issue by kyook** [bioentity/Bioentity.link#75]
https://github.com/bioentity/papers/issues/1392
https://bioentity.link/#/publication/10.17912/micropub.biology.000200 
Would it be possible to set linking to be case insensitive for a particular keyword set? 
ex. Expr_curation keywords should recognize terms in a case-insensitive fashion. WB_gartp_Seq does need case-sensitivity, so this can't be some thing that affects every keyword set.

**Comment by nickstiffler** [comment]
I added a checkbox below the italic only checkbox. If it is checked, it will link things regardless of case.

**Comment by kyook** [comment]
looks good! thanks!
